/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Comisario;
import Models.ComisarioADO;
import Models.TryParse;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ab
 */
public class ComisarioAgregar extends javax.swing.JFrame {

    /**
     * Creates new form Comisario
     */
    ResultSet rs;
    public ComisarioAgregar() {
        initComponents();
    }
    public void Habilitar(){
           this.tRun.setEnabled(true);
           this.tNombre.setEnabled(true);
           this.tAppat.setEnabled(true); 
           this.tApmat.setEnabled(true);
           this.tDireccion.setEnabled(true);
           this.tTel.setEnabled(true);
           this.tEmail.setEnabled(true);
           this.CBtc.setEnabled(true);
     }
    public void Deshabilitar(){
           this.tRun.setEnabled(false);
           this.tNombre.setEnabled(false);
           this.tAppat.setEnabled(false); 
           this.tApmat.setEnabled(false);
           this.tDireccion.setEnabled(false);
           this.tTel.setEnabled(false);
           this.tEmail.setEnabled(false);
           this.CBtc.setEnabled(false);
     }
     public void limpiar(){
           this.tRun.setText("");
           this.tCodigo.setText("");
           this.tNombre.setText("");
           this.tAppat.setText(""); 
           this.tApmat.setText("");
           this.tDireccion.setText("");
           this.tTel.setText("");
           this.tEmail.setText("");
           this.CBtc.setSelectedIndex(0);
 }
    private void cargarRegistros(){
      DefaultTableModel modelo = (DefaultTableModel) table.getModel();
      modelo.setRowCount(0);
      ComisarioADO em= new ComisarioADO();
      rs = em.Consulta("Select * from Cliente");
      try{
          while(rs.next()){
          Vector op= new Vector();
          op.add(rs.getInt(1));
          op.add(rs.getInt(2));
          op.add(rs.getString(3));
          op.add(rs.getString(4));
          op.add(rs.getString(5));
          op.add(rs.getString(6));
          op.add(rs.getBoolean(7));
          op.add(rs.getString(8));
          op.add(rs.getString(9));
          op.add(rs.getString(10));
          modelo.addRow(op);
          table.setModel(modelo);
          }
      }catch(SQLException e){
      }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        tAppat = new javax.swing.JTextField();
        CBtc = new javax.swing.JComboBox();
        tRun = new javax.swing.JTextField();
        tTel = new javax.swing.JTextField();
        tApmat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tEmail = new javax.swing.JTextField();
        tDireccion = new javax.swing.JTextField();
        tCodigo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rHombre = new javax.swing.JRadioButton();
        rMujer = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Bmodificar = new javax.swing.JButton();
        Beliminar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lblRespuesta = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tBuscar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        jLabel1.setText("Codigo :");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido mat. :");

        jLabel4.setText("Tipo Cliente :");

        jLabel5.setText("Run :");

        jLabel6.setText("Telefono :");

        jLabel7.setText("E_mail :");

        tNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tNombreKeyTyped(evt);
            }
        });

        tAppat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tAppatKeyTyped(evt);
            }
        });

        CBtc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "Casual", "Frecuente", "VIP" }));
        CBtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBtcActionPerformed(evt);
            }
        });

        tRun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tRunKeyTyped(evt);
            }
        });

        tTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tTelKeyTyped(evt);
            }
        });

        tApmat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tApmatKeyTyped(evt);
            }
        });

        jLabel8.setText("Apellido pat. :");

        jLabel9.setText("Direccion :");

        jLabel10.setText("Sexo :");

        rHombre.setText("Hombre");

        rMujer.setText("Mujer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(tApmat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tAppat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(231, 231, 231))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(tRun, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tTel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rHombre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rMujer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(CBtc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rHombre)
                    .addComponent(rMujer))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tAppat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tApmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(CBtc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BotonAgregar(evt);
            }
        });

        Bmodificar.setText("Modificar");
        Bmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmodificarActionPerformed(evt);
            }
        });

        Beliminar.setText("Eliminar");
        Beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeliminarActionPerformed(evt);
            }
        });

        jButton7.setText("Restablecer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setText("Traer datos por id");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bmodificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Beliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(Bmodificar)
                .addGap(18, 18, 18)
                .addComponent(Beliminar)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(7, 7, 7))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo Cliente", "Run", "Nombre", "Apellido pat.", "Apellido mat.", "Sexo ", "Direccion", "Telefono", "Email"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel11.setText("Buscar por:");

        tBuscar.setText("Filtro");
        tBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tBuscarFocusGained(evt);
            }
        });
        tBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBuscarActionPerformed(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(lblRespuesta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblRespuesta)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tNombreKeyTyped

    }//GEN-LAST:event_tNombreKeyTyped

    private void tAppatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tAppatKeyTyped

    }//GEN-LAST:event_tAppatKeyTyped

    private void CBtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBtcActionPerformed

    private void tRunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tRunKeyTyped

    }//GEN-LAST:event_tRunKeyTyped

    private void tTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tTelKeyTyped

    }//GEN-LAST:event_tTelKeyTyped

    private void tApmatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tApmatKeyTyped

    }//GEN-LAST:event_tApmatKeyTyped
    private String validarEntero(String valor,String nombreVariable){
    if("".equals(valor)){
        return "Debe ingresar "+ nombreVariable;
    }else{
        TryParse tr= new TryParse();
        if(tr.esEntero(valor)){
            int valorEntero= Integer.valueOf(valor);
            if(valorEntero > 0){
               return "";
            }else{
                return "Dbe ingresar "+ nombreVariable+" >0";
            }
        }else{
                return "Debe ingresar "+nombreVariable+" numerico entero";
            }
        }
    }
    private String validarFloat(String valor,String nombreVariable){
    if("".equals(valor)){
        return "Debe ingresar "+ nombreVariable;
    }else{
        TryParse tr= new TryParse();
        if(tr.esFloat(valor)){
            float valorReal= Float.valueOf(valor);
            if(valorReal > 0){
               return "";
            }else{
                return "Dbe ingresar "+ nombreVariable+" >0";
            }
        }else{
                return "Debe ingresar "+nombreVariable+" numerico Real";
            }
        }
    }
    private void jButton1BotonAgregar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BotonAgregar
        lblRespuesta.setText(validarEntero(tCodigo.getText(),"Id cliente"));
        if("".equals(lblRespuesta.getText())){
            if("".equals(tRun.getText())){
                lblRespuesta.setText("Debe ingresar un run");
                tRun.requestFocus();
            }else{
                if("".equals(tNombre.getText())){
                    lblRespuesta.setText("Debe ingresar un nombre");
                    tNombre.requestFocus();
                }else{
                    if("".equals(tAppat.getText())){
                        lblRespuesta.setText("Debe Ingresar su apellido paterno");
                        tAppat.requestFocus();
                    }else{
                        if("".equals(tApmat.getText())){
                            lblRespuesta.setText("Debe ingresar su apellido materno");
                            tApmat.requestFocus();
                        }else{
                            if("".equals(tDireccion.getText())){
                                lblRespuesta.setText("Debe ingresar una direccion");
                                tDireccion.requestFocus();
                            }else{
                                if("".equals(tTel.getText())){
                                    lblRespuesta.setText("Debe ingresar un numero de telefono");
                                    tTel.requestFocus();
                                }else{
                                    if("".equals(tEmail.getText())){
                                        lblRespuesta.setText("Debe de ingresar un email");
                                        tEmail.requestFocus();
                                    }else{
                                        if(CBtc.getSelectedIndex()==0){
                                            lblRespuesta.setText("Debe de seleccionar una opcion");
                                            CBtc.requestFocus();
                                        }else{
                                            int codigo = Integer.valueOf(tCodigo.getText());
                                            ControladorComisario cli= new ControladorComisario();
                                            lblRespuesta.setText(cli.existeCliente(codigo));
                                            if("".equals(lblRespuesta.getText())){
                                                cli.agregarCliente(codigo,CBtc.getSelectedIndex(),tRun.getText(),tNombre.getText(),tAppat.getText(),tApmat.getText(),sexoCliente(),tDireccion.getText(),tTel.getText(),tEmail.getText());
                                                lblRespuesta.setText("Cliente ha sido guardado");
                                                limpiar();
                                                tCodigo.requestFocus();
                                                cargarRegistros();

                                            }else{
                                                if(!"".equals(lblRespuesta.getText())){
                                                    lblRespuesta.setText("Id existente");
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }else{
            tCodigo.requestFocus();
        }
    }//GEN-LAST:event_jButton1BotonAgregar

    private void BmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmodificarActionPerformed
        lblRespuesta.setText(validarEntero(tCodigo.getText(),"Id cliente"));
        if("".equals(lblRespuesta.getText())){
            if("".equals(tRun.getText())){
                lblRespuesta.setText("Debe ingresar un run");
                tRun.requestFocus();
            }else{
                if("".equals(tNombre.getText())){
                    lblRespuesta.setText("Debe ingresar un nombre.");
                    tNombre.requestFocus();
                }else{
                    if("".equals(tAppat.getText())){
                        lblRespuesta.setText("Debe ingresar el apellido Paterno.");
                        tAppat.requestFocus();
                    }else{
                        if("".equals(tApmat.getText())){
                            lblRespuesta.setText("Debe ingresar un apellido Materno.");
                            tApmat.requestFocus();
                        }else{
                            if("".equals(tTel.getText())){
                                lblRespuesta.setText("Debe ingresar un numero.");
                                tTel.requestFocus();
                            }else{
                                if("".equals(tEmail.getText())){
                                    lblRespuesta.setText("Debe ingresar email.");
                                    tEmail.requestFocus();
                                }else{
                                    int codigo = Integer.valueOf(tCodigo.getText());
                                    ControladorComisario cli= new ControladorComisario();
                                    lblRespuesta.setText(cli.existeCliente(codigo));
                                    if(!"".equals(lblRespuesta.getText())){
                                        cli.actualizarCliente(codigo, CBtc.getSelectedIndex(),tRun.getText(),tNombre.getText(), tAppat.getText(),tApmat.getText(),sexoCliente(),tDireccion.getText(), tTel.getText(),tEmail.getText());
                                        lblRespuesta.setText("Cliente ha sido actualizado");
                                        limpiar();
                                        tCodigo.requestFocus();
                                        cargarRegistros();
                                    }else{
                                        if("".equals(lblRespuesta.getText())){
                                            lblRespuesta.setText("Id no existente en la BD");
                                            tCodigo.requestFocus();
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }else{
            tCodigo.requestFocus();
        }
    }//GEN-LAST:event_BmodificarActionPerformed

    private void BeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeliminarActionPerformed
        lblRespuesta.setText(validarEntero(tCodigo.getText(),"Id cliente"));
        if("".equals(lblRespuesta.getText())){
            int codigo= Integer.valueOf(tCodigo.getText());
            ControladorComisario cli= new ControladorComisario();
            lblRespuesta.setText(cli.eliminarCliente(codigo));
            if("".equals(lblRespuesta.getText())){
                lblRespuesta.setText("Los datos del cliente se han eliminado");
                tCodigo.setText("");
                tCodigo.requestFocus();
            }else{
                lblRespuesta.setText("Los datos no se han podido eliminar, reintente");
                tCodigo.requestFocus();
                tCodigo.selectAll();
            }
        }else{
            tCodigo.requestFocus();
        }
    }//GEN-LAST:event_BeliminarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        limpiar();
        cargarRegistros();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        Menu a= new Menu();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        lblRespuesta.setText(validarEntero(tCodigo.getText(),"Id Cliete"));
        if("".equals(lblRespuesta.getText())){
            int codigo=Integer.valueOf(tCodigo.getText());
            ControladorComisario cli= new ControladorComisario();
            lblRespuesta.setText(cli.existeCliente(codigo));
            if("".equals(lblRespuesta.getText())){
                lblRespuesta.setText("El id no se encuaenta en la BD");
                tCodigo.requestFocus();
            }else{
                String mensaje= lblRespuesta.getText();
                if(mensaje.indexOf("existe")==-1){
                    lblRespuesta.setText("Id cleinte no fue consultado, reintente");
                    tCodigo.requestFocus();
                    Habilitar();
                }else{
                    lblRespuesta.setText(cli.consultaxDatosUnCliente(codigo));
                    if("".equals(lblRespuesta.getText())){
                        Cliente cl;
                        cl= cli.obtenerDatosCliente();
                        CBtc.setSelectedIndex(cl.getTipoCliente());
                        tRun.setText(cl.getRun());
                        tNombre.setText(cl.getNombre());
                        tAppat.setText(cl.getAppat());
                        tApmat.setText(cl.getApmat());
                        if(cl.getSexoC()==false){
                            rHombre.setSelected(true);
                        }else{
                            rMujer.setSelected(true);
                        }
                        tDireccion.setText(cl.getDireccion());
                        tTel.setText(cl.getTel());
                        tEmail.setText(cl.getEmail());
                        Bmodificar.setEnabled(true);
                        Beliminar.setEnabled(true);
                        Habilitar();
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tBuscarFocusGained
        tBuscar.setText("");
    }//GEN-LAST:event_tBuscarFocusGained

    private void tBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBuscarActionPerformed
        tBuscar.selectAll();
    }//GEN-LAST:event_tBuscarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        while(table.getRowCount()!= 0){
            ((DefaultTableModel) table.getModel()).removeRow(0);
        }
        if("".equals(tBuscar.getText())){
            tBuscar.setText("Debe ingresar un filtro a consultar. ");

        }else{
            ControladorComisario ocp = new ControladorComisario();
            String mensaje = ocp.consultaxDatosUnClienteFiltrados(tBuscar.getText());
            if("".equals(mensaje)){ // Hay datos en base al Filtro
                DefaultTableModel modelo = (DefaultTableModel) table.getModel();
                Object [] fila = new Object[10];
                ArrayList<Comisario> listaClientes;
                listaClientes = ocp.obtenerDatosClienteFiltrados();
                for(Comisario e : listaClientes){
                    fila[0] = e.getIdCom();
                    fila[1] = e.getRunCom();
                    fila[2] = e.getNombreCom();
                    fila[3] = e.getAppatCom();
                    fila[4] = e.getApmatCom();
                    fila[5] = e.getFonoCom();
                    fila[6] = e.getEmailCom();
                    modelo.addRow(fila);
                }
            }else{
                tBuscar.setText(mensaje);
            }

        }
        tBuscar.selectAll();
        tBuscar.requestFocus();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComisarioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComisarioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComisarioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComisarioAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComisarioAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Beliminar;
    private javax.swing.JButton Bmodificar;
    private javax.swing.JComboBox CBtc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JRadioButton rHombre;
    private javax.swing.JRadioButton rMujer;
    private javax.swing.JTextField tApmat;
    private javax.swing.JTextField tAppat;
    private javax.swing.JTextField tBuscar;
    private javax.swing.JTextField tCodigo;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tRun;
    private javax.swing.JTextField tTel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
