/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import Controllers.*;

/**
 *
 * @author ab
 */
public class IniciarSesion extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        ImageIcon imagen= new ImageIcon(getClass().getResource("/Images/ini.jpg"));
        Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(lblFondo.getWidth(), lblFondo.getHeight(), Image.SCALE_DEFAULT));
        lblFondo.setIcon(icono);
        this.repaint();
        Cargar();
    }
    private void Cargar(){
        lblRespuesta.setText("");
        Tusername.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        Tusername = new javax.swing.JTextField();
        lblRespuesta = new javax.swing.JLabel();
        Biniciar = new javax.swing.JButton();
        Ppassword = new javax.swing.JPasswordField();
        Bregistro = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesion");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Username :");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        lblPassword.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password :");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, 20));

        Tusername.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jPanel1.add(Tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 130, -1));

        lblRespuesta.setFont(new java.awt.Font("Century", 1, 12)); // NOI18N
        lblRespuesta.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        Biniciar.setFont(new java.awt.Font("Bell MT", 1, 12)); // NOI18N
        Biniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iniciar-sesion.png"))); // NOI18N
        Biniciar.setText("Iniciar Sesion");
        Biniciar.setBorderPainted(false);
        Biniciar.setContentAreaFilled(false);
        Biniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Biniciar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iniciar-sesionSelected.png"))); // NOI18N
        Biniciar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Biniciar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Biniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BiniciarMouseClicked(evt);
            }
        });
        Biniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(Biniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));
        jPanel1.add(Ppassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 130, -1));

        Bregistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registro.png"))); // NOI18N
        Bregistro.setBorderPainted(false);
        Bregistro.setContentAreaFilled(false);
        Bregistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bregistro.setLabel("Registrarse");
        Bregistro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registroSelected.png"))); // NOI18N
        Bregistro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Bregistro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Bregistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BregistroMouseClicked(evt);
            }
        });
        Bregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BregistroActionPerformed(evt);
            }
        });
        jPanel1.add(Bregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BiniciarMouseClicked
        lblRespuesta.setText("");
        if("".equals(Tusername.getText())){
            lblRespuesta.setText("Ingrese el username");
            Tusername.requestFocus();
        }else{
            String llave = String.valueOf(Ppassword.getPassword());
            if("".equals(llave)){
                lblRespuesta.setText("Ingrese la Password");
                Ppassword.requestFocus();
            }else{
                ControladorAcceso ac = new ControladorAcceso();
                lblRespuesta.setText(ac.verificaCredenciales(Tusername.getText(), llave)); //Verifica username y llave existen en la BD
                if("".equals(lblRespuesta.getText())){
                    //OK
                    this.dispose();
                    new Menu().setVisible(true);
                }else{
                    lblRespuesta.setText(ac.verificaUsername(Tusername.getText())); //Verifica si Username es valido
                    if("".equals(lblRespuesta.getText())){
                        lblRespuesta.setText(ac.verificaPassword(Tusername.getText(), llave)); //Veridica llave de Username
                        Ppassword.requestFocus();
                        Ppassword.selectAll();
                    }else{
                        Tusername.requestFocus();
                        Tusername.selectAll();
                    }
                }
            }
        }
    }//GEN-LAST:event_BiniciarMouseClicked

    private void BregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BregistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BregistroActionPerformed

    private void BregistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BregistroMouseClicked
    ControladorAcceso ac= new ControladorAcceso();
    if("".equals(ac.verificaConexion())){
    new Registrarse().setVisible(true);
    this.dispose();
    }
    }//GEN-LAST:event_BregistroMouseClicked

    private void BiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Biniciar;
    private javax.swing.JButton Bregistro;
    private javax.swing.JPasswordField Ppassword;
    private javax.swing.JTextField Tusername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
